- name: Deploy parking conductor
  hosts: all
  user: root
  gather_facts: False

  vars:
    project_name: salt-redirector
    repo_url: https://github.com/128technology/hyper-128t.git
    repo_dest: /home/{{ project_name }}/hyper128t
    app_home: "{{ repo_dest }}/{{ project_name }}"

  handlers:
    - name: restart nginx
      service:
         name: nginx
         state: restarted

    - name: restart salt master
      systemd:
        name: salt-master
        state: restarted


  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install packages
      package:
        name:
          - gcc
          - git
          - nginx
          - python3-setuptools
          - python3-dev
          - python3-venv
          - python3-wheel
          - salt-master
          - sudo
        state: latest

    - name: Configure salt master
      copy:
        dest: /etc/salt/master
        content: |
            transport: tcp
            tcp_keepalive: True
            tcp_keepalive_idle: 5
            tcp_keepalive_cnt: 3
            tcp_keepalive_intvl: 20
      notify:
        - restart salt master

    - name: Install symlink for unexpected paths on Debian
      file:
        src: /var/lib/salt/pki
        dest: /etc/salt/pki
        state: link

    - name: Add user {{ project_name }}
      user:
        name: "{{ project_name }}"

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        force: yes
      become: yes
      become_user: "{{ project_name }}"

    - name: Install virtualenv and dependencies
      pip:
          requirements: "{{ app_home }}/requirements.txt"
          virtualenv: "{{ app_home }}/venv"
          virtualenv_command: python3 -m venv
      become: yes
      become_user: "{{ project_name }}"

    - name: Install systemd service
      copy:
        content: |
            [Unit]
            Description=Service to provide a GUI for accepting minion keys and redirection minions to Conductors

            [Service]
            User=salt
            WorkingDirectory={{ app_home }}
            ExecStart={{ app_home }}/{{ project_name }}.py
            Restart=on-failure
            RestartSec=5

            [Install]
            WantedBy=multi-user.target
        dest: /etc/systemd/system/{{ project_name }}.service

    - name: Enable service
      systemd:
        name: "{{ project_name }}"
        state: started
        #daemon_reload: yes

    - name: Remove nginx default page
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - restart nginx

    - name: Copy ssl config if not exists
      copy:
        src: /etc/nginx/snippets/snakeoil.conf
        dest: /etc/nginx/ssl.conf
        remote_src: yes
        force: no

    - name: Create htpasswd
      copy:
        dest: /etc/nginx/passwdfile
        content: 'jdoe:$apr1$O4/kNhFr$exVZk.BhMK99pq2eXBp3U0'
        owner: root
        group: www-data
        mode: 0640

    - name: Configure nginx
      copy:
        content: |
            server {
                listen 80;
                return 301 https://$host$request_uri;
            }
            server {
                listen 443 ssl;
                include ssl.conf;
                location / {
                    proxy_pass http://localhost:5000/;
                    auth_basic "Login required";
                    auth_basic_user_file /etc/nginx/passwdfile;
                }
                location ^~ /.well-known/acme-challenge/ {
                    root /var/www/letsencrypt/;
                }
            }
        dest: /etc/nginx/sites-available/{{ project_name }}.conf
      notify:
        - restart nginx

    - name: Enable nginx config
      file:
        src: /etc/nginx/sites-available/{{ project_name }}.conf
        dest: /etc/nginx/sites-enabled/{{ project_name }}.conf
        state: link
      notify:
        - restart nginx
